{
    "name": "Marketing Center - Website",
    "summary": "First-party Odoo Website adapter for the marketing ingress",
    "version": "16.0.2.3.0",
    "category": "Marketing",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/marketing-center",
    "license": "AGPL-3",
    "depends": [
        "web",
        "website",
        "marketing_center_base",
        "website_crm",
        "queue_job",
    ],
    "data": [
        "security/marketing_center_web_ingress_security.xml",
        "data/web_ingress_cron.xml",
        "views/web_ingress_views.xml",
        "security/marketing_center_website_security.xml",
        "security/ir.model.access.csv",
        "data/website_action_cron.xml",
        "views/website_ingress_binding_views.xml",
        "views/website_action_views.xml",
        "views/measurement_layout.xml",
        "views/website_visitor_views.xml",
        "security/marketing_center_website_crm_security.xml",
        "data/queue_job.xml",
        "data/recovery_cron.xml",
        "views/intent_views.xml",
        "views/native_submission_views.xml",
        "views/ip_observation_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "marketing_center_website/static/src/js/landing_capture.esm.js",
            "marketing_center_website/static/src/js/consent.esm.js",
            "marketing_center_website/static/src/js/landing_bootstrap.esm.js",
            "marketing_center_website/static/src/js/action_capture.esm.js",
            "marketing_center_website/static/src/js/action_bootstrap.esm.js",
            "marketing_center_website/static/src/js/measurement_context.esm.js",
            "marketing_center_website/static/src/js/measurement.esm.js",
        ],
        "web.qunit_suite_tests": [
            "marketing_center_website/static/src/js/landing_capture.esm.js",
            "marketing_center_website/static/src/js/action_capture.esm.js",
            "marketing_center_website/static/tests/landing_capture_tests.esm.js",
            "marketing_center_website/static/tests/action_capture_tests.esm.js",
        ],
    },
    "installable": True,
    "application": False,
    "pre_init_hook": "pre_init_hook",
    "uninstall_hook": "uninstall_hook",
}
