{
    "name": "Marketing Center - Dashboard",
    "summary": "Compatibility package; functionality is included in Marketing Center",
    "version": "16.0.2.0.0",
    "category": "Marketing",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/marketing-center",
    "license": "AGPL-3",
    "depends": ["marketing_center_base"],
    "data": [],
    "installable": True,
    "application": False,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
