{
    "name": "Marketing Center Base",
    "summary": "Provider-neutral marketing and attribution foundation",
    "version": "16.0.1.0.1",
    "category": "Marketing",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/marketing-center",
    "license": "AGPL-3",
    "depends": ["base", "utm"],
    "data": [
        "security/marketing_center_security.xml",
        "security/ir.model.access.csv",
        "data/sync_recovery_cron.xml",
        "data/attribution_resolution_cron.xml",
        "views/configuration_views.xml",
        "views/catalog_views.xml",
        "views/performance_views.xml",
        "views/sync_views.xml",
        "views/attribution_views.xml",
        "views/attribution_calculation_views.xml",
        "views/business_event_views.xml",
        "views/menus.xml",
        "views/attribution_resolution_views.xml",
    ],
    "installable": True,
    "application": False,
}
