{
    "name": "Marketing Center",
    "summary": "Acquisition evidence, CRM attribution and management overview",
    "version": "16.0.2.1.2",
    "category": "Marketing",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/marketing-center",
    "license": "AGPL-3",
    "depends": ["base", "utm", "crm", "queue_job"],
    "data": [
        "security/marketing_center_security.xml",
        "security/ir.model.access.csv",
        "data/sync_recovery_cron.xml",
        "data/attribution_resolution_cron.xml",
        "views/configuration_views.xml",
        "views/catalog_views.xml",
        "views/performance_views.xml",
        "views/sync_views.xml",
        "views/attribution_views.xml",
        "views/attribution_calculation_views.xml",
        "views/business_event_views.xml",
        "views/menus.xml",
        "views/campaign_board_views.xml",
        "views/attribution_resolution_views.xml",
        "views/crm/menus.xml",
        "security/crm/marketing_center_crm_security.xml",
        "security/crm/ir.model.access.csv",
        "views/crm/crm_views.xml",
        "views/crm/link_views.xml",
        "data/crm/native_utm_queue.xml",
        "security/crm/native_utm_security.xml",
        "views/crm/native_utm_views.xml",
        "views/crm/campaign_board_views.xml",
        "security/dashboard/marketing_center_dashboard_security.xml",
        "security/dashboard/ir.model.access.csv",
        "views/dashboard/dashboard_views.xml",
    ],
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
}
