{
    "name": "Marketing Center - Meta",
    "summary": "Read-only Meta Marketing API connector for Marketing Center",
    "version": "16.0.1.1.0",
    "category": "Marketing",
    "author": "Soloz Technologies",
    "website": "https://github.com/soloztech/marketing-center",
    "license": "AGPL-3",
    "depends": [
        "marketing_center_base",
        "meta_api_base",
        "meta_webhook_base",
        "queue_job",
    ],
    "data": [
        "security/marketing_center_meta_security.xml",
        "security/lead_tools_security.xml",
        "security/ir.model.access.csv",
        "data/queue_job.xml",
        "data/sync_cron.xml",
        "views/meta_profile_views.xml",
        "views/marketing_connection_views.xml",
        "views/marketing_source_views.xml",
        "views/lead_tools_views.xml",
        "views/lead_ads_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "marketing_center_meta/static/src/views/lead_route_list.esm.js",
            "marketing_center_meta/static/src/views/lead_route_list.xml",
        ],
    },
    "external_dependencies": {"python": ["requests"]},
    "installable": True,
    "application": False,
}
